# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: KWON TAE HEON (권태헌)
title: Back-End Developer
email: pcloud63514@gmail.com
phone: 010-9251-7624
website: v1.3

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  pcloud63514
stackoverflow_username: 
dribbble_username: 
facebook_username: 
flickr_username: 
instagram_username: 
linkedin_username: 
xing_username: 
pinterest_username: 
youtube_username: 
googleplus_username: 
orcid_username: 

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Profile-Image.PNG
about_content: | # this will include new lines to allow paragraphs
  재학 시절 프로그래밍에 관련된 내용이라면 전부 학습하고자 했습니다. 그 중 가장 큰 관심사는 웹 서비스 개발 이였습니다.
  다양한 기술을 학습해도 사용자에게 배포하는 과정이나 접근성을 높여야 배운 기술의 가치가 높아진다. 생각하였고 이를 충족할 수 있는 것이
  백엔드의 웹 서비스 및 안드로이드 개발이였습니다.
  재학 과정 다양한 프로젝트 경험과 학습을 뒤로하고 2017년 병역복무를 진행하였습니다. 개인적 흥미로  Tensorflow & Keras를 학습하였으며,
  이때의 지식을 활용해 2020년 복학 이후 종합설계의 "음성인식을 통한 자동 자막 제공 프로그램"을 개발하였습니다.  
  이와 함께 비슷한 주제로 관련하여 ZAISoft 회사의 현장실습을 진행하였습니다.
  현재는 취업을 위해 포트폴리오와 프로필 작성에 집중하고 있습니다.
  

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Skills
more_content: | # this will include new lines to allow paragraphs
  C# Windows Programming, Spring Framework, Android(JAVA, Kotlin).

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
